{
  "openapi": "3.0.2",
  "info": {
    "title": "Authentication.Management",
    "version": "EXAPIAUTHMGMT_1.0.0"
  },
  "servers": [
    {
      "url": "https://mtls.api.clearbank.co.uk"
    },
    {
      "url": "https://mtls.api.eu.clearbank.io"
    }
  ],
  "paths": {
    "/authentication/v1/clients/{ClientId}": {
      "post": {
        "tags": [
          "Clients"
        ],
        "summary": "Register a client",
        "security": [
          {
            "OAuth2": [
              "apis:clients:create"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Get a client",
        "security": [
          {
            "OAuth2": [
              "apis:clients:read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Clients"
        ],
        "summary": "Delete a client",
        "security": [
          {
            "OAuth2": [
              "apis:clients:delete"
            ]
          }
        ]
      }
    },
    "/authentication/v1/clients": {
      "get": {
        "tags": [
          "Clients"
        ],
        "summary": "Get all clients",
        "security": [
          {
            "OAuth2": [
              "apis:clients:read"
            ]
          }
        ]
      }
    },
    "/authentication/v1/clients/{ClientId}/scopes": {
      "get": {
        "tags": [
          "ClientScopes"
        ],
        "summary": "Get client scopes",
        "description": "Get all scopes for a client",
        "security": [
          {
            "OAuth2": [
              "apis:clients:read"
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "ClientScopes"
        ],
        "summary": "Update a client's allowed scopes",
        "security": [
          {
            "OAuth2": [
              "apis:clients:update"
            ]
          }
        ]
      }
    },
    "/authentication/v1/clients/{ClientId}/secrets": {
      "post": {
        "tags": [
          "ClientSecrets"
        ],
        "summary": "Register a client secret",
        "security": [
          {
            "OAuth2": [
              "apis:clients:create"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ClientSecrets"
        ],
        "summary": "Get client secrets",
        "description": "Get all secrets for a client",
        "security": [
          {
            "OAuth2": [
              "apis:clients:read"
            ]
          }
        ]
      }
    },
    "/authentication/v1/clients/{ClientId}/secrets/{SecretId}": {
      "delete": {
        "tags": [
          "ClientSecrets"
        ],
        "summary": "Delete a client secret",
        "security": [
          {
            "OAuth2": [
              "apis:clients:delete"
            ]
          }
        ]
      }
    },
    "/authentication/v1/clients/{ClientId}/signature-keys/{KeyId}": {
      "post": {
        "tags": [
          "ClientSignatureKeys"
        ],
        "summary": "Register a client signature key",
        "security": [
          {
            "OAuth2": [
              "apis:clients:create"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "ClientSignatureKeys"
        ],
        "summary": "Get client signature key",
        "security": [
          {
            "OAuth2": [
              "apis:clients:read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "ClientSignatureKeys"
        ],
        "summary": "Delete client signature key",
        "security": [
          {
            "OAuth2": [
              "apis:clients:delete"
            ]
          }
        ]
      }
    },
    "/authentication/v1/clients/{ClientId}/signature-keys": {
      "get": {
        "tags": [
          "ClientSignatureKeys"
        ],
        "summary": "Get client signature keys",
        "security": [
          {
            "OAuth2": [
              "apis:clients:read"
            ]
          }
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2"
      }
    }
  },
  "tags": [
    {
      "name": "Clients"
    },
    {
      "name": "ClientScopes"
    },
    {
      "name": "ClientSecrets"
    },
    {
      "name": "ClientSignatureKeys"
    }
  ]
}